[tool.black]
line-length = 120
exclude = """

"""

[tool.isort]
line_length = 120
profile = "black"

[tool.pylint.MASTER]
py-version=3.7

[tool.pylint.FORMAT]
max-line-length=120

[tool.pylint.'MESSAGES CONTROL']
disable="""
    duplicate-code,
    not-context-manager,
"""

[tool.coverage.run]
omit = [
  "tests/*",
  "setup.py"
]
